services:

  init_data:
    extends:
      file: docker-compose.yml
      service: init_data
    profiles:
      - "node"

  api:
    extends:
      file: docker-compose.yml
      service: api
    profiles:
      - "node"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      VIRTUAL_HOST: ${NB_NAPI_DOMAIN}
      VIRTUAL_PATH: ${NB_NAPI_BASE_PATH:-/}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${NB_NAPI_DOMAIN}
    networks:
      - proxy-net
      - default
  
  graph:
    extends:
      file: docker-compose.yml
      service: graph
    profiles:
      - "node"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    networks:
      - default

  federation:
    extends:
      file: docker-compose.yml
      service: federation
    profiles:
      - "portal"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      VIRTUAL_HOST: ${NB_FAPI_DOMAIN}
      VIRTUAL_PATH: ${NB_FAPI_BASE_PATH:-/}
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: ${NB_FAPI_DOMAIN}
    networks:
      - proxy-net

  query_federation:
    extends:
      file: docker-compose.yml
      service: query_federation
    profiles:
      - "portal"
    # For a production deployment, we want to avoid binding ports to the host to avoid conflicts with
    # already running services. So here we override the ports exposed in the recipe we expand from and
    # set the ports to an empty list
    ports: !override []
    environment:
      NB_API_QUERY_URL: https://${NB_FAPI_DOMAIN}${NB_FAPI_BASE_PATH}
      VIRTUAL_HOST: ${NB_QUERY_DOMAIN}
      VIRTUAL_PATH: ${NB_QUERY_APP_BASE_PATH:-/}
      VIRTUAL_PORT: 5173
      LETSENCRYPT_HOST: ${NB_QUERY_DOMAIN}
    networks:
      - proxy-net

secrets:
  db_admin_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    file: ${NB_GRAPH_SECRETS_PATH:-./secrets}/NB_GRAPH_PASSWORD.txt

volumes:
  graphdb_home:
  neurobagel_data:

networks:
  proxy-net:
    external: true
    name: NB_proxynet